language: node_js
node_js:
  - 10
env:
  global:
    - DB_USER=postgres
    - DB_PORT=5432
    - DB_PASSWORD=
    - DB_HOST=localhost
    - DB_DATABASE=votejs
    - ENCRYPTION_KEY=crypto-key-exactly-32-chars-long
before_install:
  - sudo service postgresql restart
install:
  npm install
cache:
  directories:
    - "node_modules"
before_script:
  - psql -c 'CREATE DATABASE votejs' -U postgres
script:
  - npm run db:up
  - npm run db:seed
  - npm run no-circular-dependecies
  - npm run lint
  - npm run test
