language: node_js
node_js:
  - 10
install:
  npm install
cache:
  directories:
    - "node_modules"
before_script:
  - psql -c 'create database votejs' -U postgres
before_install:
  - sudo service postgresql restart
env:
  global:
    - DB_USER=postgres
    - DB_PORT=5432
    - DB_PASSWORD=
    - DB_HOST=localhost
    - DB_DATABASE=votejs
script:
  - npm run db:up
  - npm run db:seed
  - npm run no-circular-dependecies
  - npm run lint
  - npm run test
